MODEL_PARAMS = \
{ 'aggregationInfo': { 'days': 0,
                       'fields': [],
                       'hours': 0,
                       'microseconds': 0,
                       'milliseconds': 0,
                       'minutes': 0,
                       'months': 0,
                       'seconds': 0,
                       'weeks': 0,
                       'years': 0},
  'model': 'CLA',
  'modelParams': { 'anomalyParams': { u'anomalyCacheRecords': None,
                                      u'autoDetectThreshold': None,
                                      u'autoDetectWaitRecords': None},
                   'clParams': { 'alpha': 0.014085570221302232,
                                 'clVerbosity': 0,
                                 'regionName': 'CLAClassifierRegion',
                                 'steps': '1'},
                   'inferenceType': 'TemporalMultiStep',
                   'sensorParams': { 'encoders': { '_classifierInput': { 'classifierOnly': True,
                                                                         'fieldname': 'bit_10',
                                                                         'n': 121,
                                                                         'name': '_classifierInput',
                                                                         'type': 'SDRCategoryEncoder',
                                                                         'w': 21},
                                                   u'bit_0': None,
                                                   u'bit_1': None,
                                                   u'bit_2': None,
                                                   u'bit_3': None,
                                                   u'bit_4': None,
                                                   u'bit_5': None,
                                                   u'bit_6': None,
                                                   u'bit_7': None,
                                                   u'bit_8': None,
                                                   u'bit_9': { 'fieldname': 'bit_9',
                                                                'n': 121,
                                                                'name': 'bit_9',
                                                                'type': 'SDRCategoryEncoder',
                                                                'w': 21},
                                                   u'bit_10': { 'fieldname': 'bit_10',
                                                                'n': 121,
                                                                'name': 'bit_10',
                                                                'type': 'SDRCategoryEncoder',
                                                                'w': 21},
                                                   u'bit_11': { 'fieldname': 'bit_11',
                                                                'n': 121,
                                                                'name': 'bit_11',
                                                                'type': 'SDRCategoryEncoder',
                                                                'w': 21},
                                                   u'bit_12': None,
                                                   u'bit_13': None,
                                                   u'bit_14': None,
                                                   u'bit_15': None,
                                                   u'bit_16': None,
                                                   u'bit_17': None,
                                                   u'bit_18': None,
                                                   u'bit_19': None,
                                                   u'bit_20': None,
                                     },
                                     'sensorAutoReset': None,
                                     'verbosity': 0},
                   'spEnable': True,
                   'spParams': { 'columnCount': 2048,
                                 'globalInhibition': 1,
                                 'inputWidth': 0,
                                 'maxBoost': 2.0,
                                 'numActiveColumnsPerInhArea': 40,
                                 'potentialPct': 0.8,
                                 'seed': 1956,
                                 'spVerbosity': 0,
                                 'spatialImp': 'cpp',
                                 'synPermActiveInc': 0.05,
                                 'synPermConnected': 0.1,
                                 'synPermInactiveDec': 0.08623331311119026},
                   'tpEnable': True,
                   'tpParams': { 'activationThreshold': 12,
                                 'cellsPerColumn': 32,
                                 'columnCount': 2048,
                                 'globalDecay': 0.0,
                                 'initialPerm': 0.21,
                                 'inputWidth': 2048,
                                 'maxAge': 0,
                                 'maxSegmentsPerCell': 128,
                                 'maxSynapsesPerSegment': 32,
                                 'minThreshold': 9,
                                 'newSynapseCount': 20,
                                 'outputType': 'normal',
                                 'pamLength': 1,
                                 'permanenceDec': 0.1,
                                 'permanenceInc': 0.1,
                                 'seed': 1960,
                                 'temporalImp': 'cpp',
                                 'verbosity': 0},
                   'trainSPNetOnlyIfRequested': False},
  'predictAheadTime': None,
  'version': 1}